### ISSUE TITLE
flexy-pool-core-java9 requires Java 9, but should require Java 8 according to the documentiation

### ISSUE THREAD

**Issue by losar** [vladmihalcea/flexy-pool#51]
Major version number of class file is 53, which leads to errors when used with JRE 8.

```
Couldn't load ConnectionDecoratorFactoryService on the current JVM
java.lang.UnsupportedClassVersionError: com/vladmihalcea/flexypool/connection/Java9ConnectionDecoratorFactoryService 
has been compiled by a more recent version of the Java Runtime (class file version 53.0), 
this version of the Java Runtime only recognizes class file versions up to 52.0 
(unable to load class [com.vladmihalcea.flexypool.connection.Java9ConnectionDecoratorFactoryService])
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2342) ~[catalina.jar:8.5.32]
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:829) ~[catalina.jar:8.5.32]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278) ~[catalina.jar:8.5.32]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137) ~[catalina.jar:8.5.32]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_181]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_181]
	at com.vladmihalcea.flexypool.connection.ConnectionDecoratorFactoryResolver.resolve(ConnectionDecoratorFactoryResolver.java:38) ~[flexy-pool-core-2.0.0.jar:?]
...
```

**Comment by vladmihalcea** [comment]
Fixed in the README file.
